apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
    helm.sh/resource-policy: keep
  name: ackclusterconfigs.ack.cattle.io
spec:
  group: ack.cattle.io
  names:
    kind: ACKClusterConfig
    plural: ackclusterconfigs
    shortNames:
      - ackcc
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            access_key_id:
              nullable: true
              type: string
            access_key_secret:
              nullable: true
              type: string
            cloud_monitor_flags:
              type: boolean
            cluster_id:
              nullable: true
              type: string
            cluster_type:
              nullable: true
              type: string
            container_cidr:
              nullable: true
              type: string
            disable_rollback:
              type: boolean
            endpoint_public_access:
              type: boolean
            imported:
              type: boolean
            key_pair:
              nullable: true
              type: string
            kubernetes_version:
              nullable: true
              type: string
            login_password:
              nullable: true
              type: string
            master_auto_renew:
              type: boolean
            master_auto_renew_period:
              type: integer
            master_instance_charge_type:
              nullable: true
              type: string
            master_instance_types:
              items:
                nullable: true
                type: string
              nullable: true
              type: array
            master_period:
              type: integer
            master_period_unit:
              nullable: true
              type: string
            master_system_disk_category:
              nullable: true
              type: string
            master_system_disk_size:
              type: integer
            master_vswitch_ids:
              items:
                nullable: true
                type: string
              nullable: true
              type: array
            name:
              nullable: true
              type: string
            node_cidr_mask:
              type: integer
            node_pools:
              items:
                properties:
                  auto_renew:
                    type: boolean
                  auto_renew_period:
                    type: integer
                  data_disk:
                    items:
                      properties:
                        auto_snapshot_policy_id:
                          nullable: true
                          type: string
                        category:
                          nullable: true
                          type: string
                        encrypted:
                          nullable: true
                          type: string
                        size:
                          type: integer
                      type: object
                    nullable: true
                    type: array
                  eip_bandwidth:
                    type: integer
                  eip_internet_charge_type:
                    nullable: true
                    type: string
                  instance_charge_type:
                    nullable: true
                    type: string
                  instance_types:
                    items:
                      nullable: true
                      type: string
                    nullable: true
                    type: array
                  instances_num:
                    type: integer
                  is_bond_eip:
                    type: boolean
                  key_pair:
                    nullable: true
                    type: string
                  login_password:
                    nullable: true
                    type: string
                  name:
                    nullable: true
                    type: string
                  nodepool_id:
                    nullable: true
                    type: string
                  period:
                    type: integer
                  period_unit:
                    nullable: true
                    type: string
                  platform:
                    nullable: true
                    type: string
                  scaling_type:
                    nullable: true
                    type: string
                  system_disk_category:
                    nullable: true
                    type: string
                  system_disk_size:
                    type: integer
                  v_switch_ids:
                    items:
                      nullable: true
                      type: string
                    nullable: true
                    type: array
                type: object
              nullable: true
              type: array
            os_type:
              nullable: true
              type: string
            platform:
              nullable: true
              type: string
            proxy_mode:
              nullable: true
              type: string
            region_id:
              nullable: true
              type: string
            resource_group_id:
              nullable: true
              type: string
            security_group_id:
              nullable: true
              type: string
            service_cidr:
              nullable: true
              type: string
            snat_entry:
              type: boolean
            ssh_flags:
              type: boolean
            timeout_mins:
              type: integer
            vpcid:
              nullable: true
              type: string
            vswitch_ids:
              items:
                nullable: true
                type: string
              nullable: true
              type: array
            zoneid:
              nullable: true
              type: string
          type: object
        status:
          properties:
            failureMessage:
              nullable: true
              type: string
            phase:
              nullable: true
              type: string
          type: object
      type: object
  version: v1
  versions:
    - name: v1
      served: true
      storage: true
