kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ack-operator
  namespace: cattle-system
rules:
  - apiGroups: ['']
    resources: ['secrets']
    verbs: ['get', 'list', 'create', 'watch']
  - apiGroups: ['ack.cattle.io']
    resources: ['ackclusterconfigs']
    verbs: ['get', 'list', 'update', 'watch']
  - apiGroups: ['ack.cattle.io']
    resources: ['ackclusterconfigs/status']
    verbs: ['update']
