apiVersion: apps/v1
kind: Deployment
metadata:
  name: ack-config-operator
  namespace: cattle-system
spec:
  replicas: 1
  selector:
    matchLabels:
      ke.cattle.io/operator: ack
  template:
    metadata:
      labels:
        ke.cattle.io/operator: ack
    spec:
      serviceAccountName: ack-operator
      containers:
      - name: ack-operator
        image: {{ template "system_default_registry" . }}{{ .Values.ackOperator.image.repository }}:{{ .Values.ackOperator.image.tag }}
        imagePullPolicy: IfNotPresent
        env:
        - name: HTTP_PROXY
          value: {{ .Values.httpProxy }}
        - name: HTTPS_PROXY
          value: {{ .Values.httpsProxy }}
        - name: NO_PROXY
          value: {{ .Values.noProxy }}
